version: "3"

services:
  node-dev:
    build: .
    image: "node:lts-hydrogen"
    container_name: "MQTT-web-bashboard"
    stdin_open: true
    tty: true
    volumes:
      - ..:/app
    working_dir: "/app"
